### ISSUE TITLE
Complete please!

### ISSUE THREAD

**Issue by naitsirc97** [typicalname0/myspace-clone#1]
Hi, you did a wonderful job! I love old MySpace! The "comments" and "blogs" section is missing in the code you released here on Github. I hope you will and maybe even release the "Twiter" code. Thank you.

**Comment by typicalname0** [comment]
I will update the source code and add twitter to a repository when im back at home.

**Comment by naitsirc97** [comment]
Ok! Thanks mate! :-)

**Comment by typicalname0** [comment]
Done!
